				</td>
			</tr>
			</table>
		<br>

		</td>
		<!-- End Left Body -->

		<!-- Right Body -->
		<td valign="top" width="20%">

		<?php
		/*
		<!-- ??? -->
		<table cellpadding="0" cellspacing="0" border="1" bordercolorlight="black" bordercolordark="white" bgcolor="#B0D7FA" width="100%" align="center">
		<tr>
			<td>Just an idea.</td>
		</tr>
		</table><br>
		<!-- End ??? -->

		<!-- ??? -->
		<table cellpadding="0" cellspacing="0" border="1" bordercolorlight="black" bordercolordark="white" bgcolor="#B0D7FA" width="100%" align="center">
		<tr>
			<td>Just an idea.</td>
		</tr>
		</table>
		<!-- End ??? -->
		*/
		?>

		</td>
		<!-- End Right Body -->
	</tr>
	</table>
	<!-- End Body Table -->

	</td>
	<!-- End Body -->

</tr>
</table>
<!-- End Main -->

</body>
</html>
