<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>

<HEAD>
<TITLE>Simple DirectMedia Layer</TITLE>
<META content="text/html; charset=iso-8859-1" http-equiv=Content-Type>
<META content="handmade PHP code" name=GENERATOR>
<STYLE type="text/css">
<!--
INPUT, TEXTAREA { font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif; }
-->
</STYLE>
</HEAD>

<BODY background="/images/beige01.jpg">
<TABLE border=0>
<TBODY>
<TR>
<TD rowSpan=2 vAlign=top>
<!-- SIDEBAR BEGINS HERE -->
<P align=center>
<A href="/index.php"><IMG alt="SDL now!" border=0 height=50 src="/images/SDL_now.gif" width=88></A>
</P>
<DL>
<DT><FONT color="#414141" size=4>&nbsp;&nbsp;&nbsp;<STRONG>German Site</STRONG></FONT>
<DD><A href="http://www.libsdl.de/"><FONT color="#414141"><STRONG>www.libsdl.de</STRONG></FONT></A>
</DD>
</DL>
<DL>
<DT><FONT color="#414141" size=4>&nbsp;&nbsp;&nbsp;<STRONG>Documentation</STRONG></FONT> 
<DD><A href="/license.php"><FONT color="#414141"><STRONG>Licensing</STRONG></FONT></A>
</DD>
<DD><A href="/docs.php"><FONT color="#414141"><STRONG>Downloadable</STRONG></FONT></A>
</DD>
<DD><A href="/intro.php"><FONT color="#414141"><STRONG>Introduction</STRONG></FONT></A>
</DD>
<DD><A href="/tutorials.php"><FONT color="#414141"><STRONG>Tutorials</STRONG></FONT></A> 
</DD>
<DD><A href="http://sdldoc.csn.ul.ie/"><FONT color="#414141"><STRONG>Doc Project</STRONG></FONT></A> 
</DD>
<DD><A href="/faq.php"><FONT color="#414141"><STRONG>FAQs</STRONG></FONT></A> 
</DD>
<DD><A href="/opengl/index.php"><FONT color="#414141"><STRONG>OpenGL</STRONG></FONT></A> 
</DD>
<DD><A href="/credits.php"><FONT color="#414141"><STRONG>Credits</STRONG></FONT></A>
</DD>
<DD><A href="/mailing-list.php"><FONT color="#414141"><STRONG>Mailing Lists</STRONG></FONT></A>
<DD><A href="http://news.gmane.org/thread.php?group=gmane.comp.lib.sdl"><FONT color="#414141"><STRONG>Newsgroup</STRONG></FONT></A>
</DD>
<FORM method="post" action="/search.php">
    <INPUT type="submit" value="Search Site"><BR>
    <INPUT type="text" name="keywords" size="12">
</FORM>
</DL>
<DL>
<DT><FONT color="#414141" size=4>&nbsp;&nbsp;&nbsp;<STRONG>Download</STRONG></FONT> 
<DD><A href="/download-1.0.php"><FONT color="#414141"><STRONG>SDL 1.0</STRONG></FONT></A> 
<DD><A href="/download-1.2.php"><FONT color="#414141"><STRONG>SDL 1.2</STRONG></FONT></A> 
<DD><A href="/cvs.php"><FONT color="#414141"><STRONG>SDL CVS</STRONG></FONT></A> 
<DD><A href="/games.php"><FONT color="#414141"><STRONG>Games</STRONG></FONT></A> 
<DD><A href="/demos.php"><FONT color="#414141"><STRONG>Demos</STRONG></FONT></A>
<DD><A href="/applications.php"><FONT color="#414141"><STRONG>Applications</STRONG></FONT></A> 
<DD><A href="/libraries.php"><FONT color="#414141"><STRONG>Libraries</STRONG></FONT></A>
</DL>
<DL>
<DT><FONT color="#414141" size=4>&nbsp;&nbsp;&nbsp;<STRONG>Related Links</STRONG></FONT> 
<DD><A href="/articles.php"><FONT color="#414141"><STRONG>Articles</STRONG></FONT></A> 
<DD><A href="http://kokido.sourceforge.net/SDL.html"><FONT color="#414141"><STRONG>SDL on IRC</STRONG></FONT></A> 
<DD><A href="http://www.geekcomix.com/snh/files/docs/sdl-kdev/sdl-kdev-mini-how2.html"><FONT color="#414141"><STRONG>SDL &amp; Kdevelop</STRONG></FONT></A> 
<DD><A href="/languages.php"><FONT color="#414141"><STRONG>SDL Languages</STRONG></FONT></A>
</DL>
<DL>
<DT>&nbsp;&nbsp;&nbsp;<STRONG><A href="/finances.php"><FONT color="#414141" size=3>SDL Finances</FONT></A></STRONG>
</DL>
<?PHP
// IGNORE THIS COMMENT HACK <!--
	include("siteactions.php");
?>
<!-- THE END OF THE COMMENT HACK -->
<DL>
<DT>&nbsp;&nbsp;&nbsp;<STRONG><A href="mailto:slouken@libsdl.org"><FONT color="#414141" size=3>Send Feedback!</FONT></A></STRONG>
</DL>
</TD>
<TD valign=top>
<!-- CONTENT BEGINS HERE -->
<!-- The following nutty code is so this works with PHP and raw HTML -->
<?PHP
	if (!$mainpage)
		echo <<<EOT
<!-- BEGINNING OF CONTENT TABLE -->
<TABLE border=0 cellPadding=15>
<TBODY>
<TR>
<TD bgColor="#fff8dc" vAlign=top>
<!--
EOT;
?>
<!-- THE END OF THE COMMENT HACK -->
